// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart_beat.proto

package com.chatnow.core.domain.protobuf.command;

public final class HeartBeat {
  private HeartBeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeartBeatCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chatnow.core.domain.protobuf.command.HeartBeatCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code com.chatnow.core.domain.protobuf.command.HeartBeatCommand}
   */
  public  static final class HeartBeatCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chatnow.core.domain.protobuf.command.HeartBeatCommand)
      HeartBeatCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatCommand.newBuilder() to construct.
    private HeartBeatCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatCommand() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartBeatCommand();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand.class, com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeSInt32(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand)) {
        return super.equals(obj);
      }
      com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand other = (com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand) obj;

      if (getType()
          != other.getType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chatnow.core.domain.protobuf.command.HeartBeatCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chatnow.core.domain.protobuf.command.HeartBeatCommand)
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand.class, com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand.Builder.class);
      }

      // Construct using com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_descriptor;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand getDefaultInstanceForType() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand build() {
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand buildPartial() {
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand result = new com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand) {
          return mergeFrom((com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand other) {
        if (other == com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>sint32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chatnow.core.domain.protobuf.command.HeartBeatCommand)
    }

    // @@protoc_insertion_point(class_scope:com.chatnow.core.domain.protobuf.command.HeartBeatCommand)
    private static final com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand();
    }

    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatCommand>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatCommand>() {
      @java.lang.Override
      public HeartBeatCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HeartBeatCommandRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chatnow.core.domain.protobuf.command.HeartBeatCommandResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    int getType();
  }
  /**
   * Protobuf type {@code com.chatnow.core.domain.protobuf.command.HeartBeatCommandResp}
   */
  public  static final class HeartBeatCommandResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chatnow.core.domain.protobuf.command.HeartBeatCommandResp)
      HeartBeatCommandRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeartBeatCommandResp.newBuilder() to construct.
    private HeartBeatCommandResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeartBeatCommandResp() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeartBeatCommandResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatCommandResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp.class, com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeSInt32(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp)) {
        return super.equals(obj);
      }
      com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp other = (com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp) obj;

      if (getType()
          != other.getType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chatnow.core.domain.protobuf.command.HeartBeatCommandResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chatnow.core.domain.protobuf.command.HeartBeatCommandResp)
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp.class, com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp.Builder.class);
      }

      // Construct using com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_descriptor;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp getDefaultInstanceForType() {
        return com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp build() {
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp buildPartial() {
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp result = new com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp(this);
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp) {
          return mergeFrom((com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp other) {
        if (other == com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>sint32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chatnow.core.domain.protobuf.command.HeartBeatCommandResp)
    }

    // @@protoc_insertion_point(class_scope:com.chatnow.core.domain.protobuf.command.HeartBeatCommandResp)
    private static final com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp();
    }

    public static com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeartBeatCommandResp>
        PARSER = new com.google.protobuf.AbstractParser<HeartBeatCommandResp>() {
      @java.lang.Override
      public HeartBeatCommandResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatCommandResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeartBeatCommandResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatCommandResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chatnow.core.domain.protobuf.command.HeartBeat.HeartBeatCommandResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020heart_beat.proto\022(com.chatnow.core.dom" +
      "ain.protobuf.command\" \n\020HeartBeatCommand" +
      "\022\014\n\004type\030\001 \001(\021\"$\n\024HeartBeatCommandResp\022\014" +
      "\n\004type\030\001 \001(\021b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommand_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chatnow_core_domain_protobuf_command_HeartBeatCommandResp_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
