// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: join_group.proto

package com.chatnow.core.domain.protobuf.command;

public final class JoinGroup {
  private JoinGroup() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JoinGroupCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chatnow.core.domain.protobuf.command.JoinGroupCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>string groupName = 2;</code>
     * @return The groupName.
     */
    java.lang.String getGroupName();
    /**
     * <code>string groupName = 2;</code>
     * @return The bytes for groupName.
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code com.chatnow.core.domain.protobuf.command.JoinGroupCommand}
   */
  public  static final class JoinGroupCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chatnow.core.domain.protobuf.command.JoinGroupCommand)
      JoinGroupCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JoinGroupCommand.newBuilder() to construct.
    private JoinGroupCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JoinGroupCommand() {
      groupName_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JoinGroupCommand();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JoinGroupCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readSInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              groupName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand.class, com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int GROUPNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object groupName_;
    /**
     * <code>string groupName = 2;</code>
     * @return The groupName.
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      }
    }
    /**
     * <code>string groupName = 2;</code>
     * @return The bytes for groupName.
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeSInt32(1, type_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupName_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, type_);
      }
      if (!getGroupNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, groupName_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand)) {
        return super.equals(obj);
      }
      com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand other = (com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand) obj;

      if (getType()
          != other.getType()) return false;
      if (!getGroupName()
          .equals(other.getGroupName())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGroupName().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chatnow.core.domain.protobuf.command.JoinGroupCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chatnow.core.domain.protobuf.command.JoinGroupCommand)
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand.class, com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand.Builder.class);
      }

      // Construct using com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        groupName_ = "";

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_descriptor;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand getDefaultInstanceForType() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand build() {
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand buildPartial() {
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand result = new com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand(this);
        result.type_ = type_;
        result.groupName_ = groupName_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand) {
          return mergeFrom((com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand other) {
        if (other == com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getGroupName().isEmpty()) {
          groupName_ = other.groupName_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>sint32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object groupName_ = "";
      /**
       * <code>string groupName = 2;</code>
       * @return The groupName.
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string groupName = 2;</code>
       * @return The bytes for groupName.
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string groupName = 2;</code>
       * @param value The groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string groupName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupName() {
        
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      /**
       * <code>string groupName = 2;</code>
       * @param value The bytes for groupName to set.
       * @return This builder for chaining.
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 3;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chatnow.core.domain.protobuf.command.JoinGroupCommand)
    }

    // @@protoc_insertion_point(class_scope:com.chatnow.core.domain.protobuf.command.JoinGroupCommand)
    private static final com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand();
    }

    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JoinGroupCommand>
        PARSER = new com.google.protobuf.AbstractParser<JoinGroupCommand>() {
      @java.lang.Override
      public JoinGroupCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinGroupCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JoinGroupCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JoinGroupCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JoinGroupCommandRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chatnow.core.domain.protobuf.command.JoinGroupCommandResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>sint32 resultCode = 2;</code>
     * @return The resultCode.
     */
    int getResultCode();
  }
  /**
   * Protobuf type {@code com.chatnow.core.domain.protobuf.command.JoinGroupCommandResp}
   */
  public  static final class JoinGroupCommandResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chatnow.core.domain.protobuf.command.JoinGroupCommandResp)
      JoinGroupCommandRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JoinGroupCommandResp.newBuilder() to construct.
    private JoinGroupCommandResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JoinGroupCommandResp() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JoinGroupCommandResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JoinGroupCommandResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readSInt32();
              break;
            }
            case 16: {

              resultCode_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp.class, com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int RESULTCODE_FIELD_NUMBER = 2;
    private int resultCode_;
    /**
     * <code>sint32 resultCode = 2;</code>
     * @return The resultCode.
     */
    public int getResultCode() {
      return resultCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeSInt32(1, type_);
      }
      if (resultCode_ != 0) {
        output.writeSInt32(2, resultCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, type_);
      }
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, resultCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp)) {
        return super.equals(obj);
      }
      com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp other = (com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp) obj;

      if (getType()
          != other.getType()) return false;
      if (getResultCode()
          != other.getResultCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResultCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chatnow.core.domain.protobuf.command.JoinGroupCommandResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chatnow.core.domain.protobuf.command.JoinGroupCommandResp)
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp.class, com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp.Builder.class);
      }

      // Construct using com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        resultCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_descriptor;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp getDefaultInstanceForType() {
        return com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp build() {
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp buildPartial() {
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp result = new com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp(this);
        result.type_ = type_;
        result.resultCode_ = resultCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp) {
          return mergeFrom((com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp other) {
        if (other == com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>sint32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int resultCode_ ;
      /**
       * <code>sint32 resultCode = 2;</code>
       * @return The resultCode.
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>sint32 resultCode = 2;</code>
       * @param value The resultCode to set.
       * @return This builder for chaining.
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 resultCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chatnow.core.domain.protobuf.command.JoinGroupCommandResp)
    }

    // @@protoc_insertion_point(class_scope:com.chatnow.core.domain.protobuf.command.JoinGroupCommandResp)
    private static final com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp();
    }

    public static com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JoinGroupCommandResp>
        PARSER = new com.google.protobuf.AbstractParser<JoinGroupCommandResp>() {
      @java.lang.Override
      public JoinGroupCommandResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinGroupCommandResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JoinGroupCommandResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JoinGroupCommandResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chatnow.core.domain.protobuf.command.JoinGroup.JoinGroupCommandResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020join_group.proto\022(com.chatnow.core.dom" +
      "ain.protobuf.command\"B\n\020JoinGroupCommand" +
      "\022\014\n\004type\030\001 \001(\021\022\021\n\tgroupName\030\002 \001(\t\022\r\n\005tok" +
      "en\030\003 \001(\t\"8\n\024JoinGroupCommandResp\022\014\n\004type" +
      "\030\001 \001(\021\022\022\n\nresultCode\030\002 \001(\021b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommand_descriptor,
        new java.lang.String[] { "Type", "GroupName", "Token", });
    internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chatnow_core_domain_protobuf_command_JoinGroupCommandResp_descriptor,
        new java.lang.String[] { "Type", "ResultCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
