// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: send_to_user.proto

package com.chatnow.core.domain.protobuf.command;

public final class SendToUser {
  private SendToUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SendToUserCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chatnow.core.domain.protobuf.command.SendToUserCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>string receiveUserName = 2;</code>
     * @return The receiveUserName.
     */
    java.lang.String getReceiveUserName();
    /**
     * <code>string receiveUserName = 2;</code>
     * @return The bytes for receiveUserName.
     */
    com.google.protobuf.ByteString
        getReceiveUserNameBytes();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string token = 4;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 4;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code com.chatnow.core.domain.protobuf.command.SendToUserCommand}
   */
  public  static final class SendToUserCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chatnow.core.domain.protobuf.command.SendToUserCommand)
      SendToUserCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendToUserCommand.newBuilder() to construct.
    private SendToUserCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendToUserCommand() {
      receiveUserName_ = "";
      content_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SendToUserCommand();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendToUserCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readSInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              receiveUserName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand.class, com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int RECEIVEUSERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object receiveUserName_;
    /**
     * <code>string receiveUserName = 2;</code>
     * @return The receiveUserName.
     */
    public java.lang.String getReceiveUserName() {
      java.lang.Object ref = receiveUserName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiveUserName_ = s;
        return s;
      }
    }
    /**
     * <code>string receiveUserName = 2;</code>
     * @return The bytes for receiveUserName.
     */
    public com.google.protobuf.ByteString
        getReceiveUserNameBytes() {
      java.lang.Object ref = receiveUserName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiveUserName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 4;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 4;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 4;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeSInt32(1, type_);
      }
      if (!getReceiveUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, receiveUserName_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, type_);
      }
      if (!getReceiveUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, receiveUserName_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand)) {
        return super.equals(obj);
      }
      com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand other = (com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand) obj;

      if (getType()
          != other.getType()) return false;
      if (!getReceiveUserName()
          .equals(other.getReceiveUserName())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + RECEIVEUSERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getReceiveUserName().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chatnow.core.domain.protobuf.command.SendToUserCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chatnow.core.domain.protobuf.command.SendToUserCommand)
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand.class, com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand.Builder.class);
      }

      // Construct using com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        receiveUserName_ = "";

        content_ = "";

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_descriptor;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand getDefaultInstanceForType() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand build() {
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand buildPartial() {
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand result = new com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand(this);
        result.type_ = type_;
        result.receiveUserName_ = receiveUserName_;
        result.content_ = content_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand) {
          return mergeFrom((com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand other) {
        if (other == com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getReceiveUserName().isEmpty()) {
          receiveUserName_ = other.receiveUserName_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>sint32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object receiveUserName_ = "";
      /**
       * <code>string receiveUserName = 2;</code>
       * @return The receiveUserName.
       */
      public java.lang.String getReceiveUserName() {
        java.lang.Object ref = receiveUserName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiveUserName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiveUserName = 2;</code>
       * @return The bytes for receiveUserName.
       */
      public com.google.protobuf.ByteString
          getReceiveUserNameBytes() {
        java.lang.Object ref = receiveUserName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiveUserName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiveUserName = 2;</code>
       * @param value The receiveUserName to set.
       * @return This builder for chaining.
       */
      public Builder setReceiveUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiveUserName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiveUserName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiveUserName() {
        
        receiveUserName_ = getDefaultInstance().getReceiveUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string receiveUserName = 2;</code>
       * @param value The bytes for receiveUserName to set.
       * @return This builder for chaining.
       */
      public Builder setReceiveUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiveUserName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 4;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 4;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 4;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 4;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chatnow.core.domain.protobuf.command.SendToUserCommand)
    }

    // @@protoc_insertion_point(class_scope:com.chatnow.core.domain.protobuf.command.SendToUserCommand)
    private static final com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand();
    }

    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendToUserCommand>
        PARSER = new com.google.protobuf.AbstractParser<SendToUserCommand>() {
      @java.lang.Override
      public SendToUserCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendToUserCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendToUserCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendToUserCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendToUserCommandRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.chatnow.core.domain.protobuf.command.SendToUserCommandResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>sint32 resultCode = 2;</code>
     * @return The resultCode.
     */
    int getResultCode();
  }
  /**
   * Protobuf type {@code com.chatnow.core.domain.protobuf.command.SendToUserCommandResp}
   */
  public  static final class SendToUserCommandResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.chatnow.core.domain.protobuf.command.SendToUserCommandResp)
      SendToUserCommandRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendToUserCommandResp.newBuilder() to construct.
    private SendToUserCommandResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendToUserCommandResp() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SendToUserCommandResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendToUserCommandResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              type_ = input.readSInt32();
              break;
            }
            case 16: {

              resultCode_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp.class, com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>sint32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int RESULTCODE_FIELD_NUMBER = 2;
    private int resultCode_;
    /**
     * <code>sint32 resultCode = 2;</code>
     * @return The resultCode.
     */
    public int getResultCode() {
      return resultCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeSInt32(1, type_);
      }
      if (resultCode_ != 0) {
        output.writeSInt32(2, resultCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, type_);
      }
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(2, resultCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp)) {
        return super.equals(obj);
      }
      com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp other = (com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp) obj;

      if (getType()
          != other.getType()) return false;
      if (getResultCode()
          != other.getResultCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResultCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.chatnow.core.domain.protobuf.command.SendToUserCommandResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.chatnow.core.domain.protobuf.command.SendToUserCommandResp)
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp.class, com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp.Builder.class);
      }

      // Construct using com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        resultCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_descriptor;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp getDefaultInstanceForType() {
        return com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp build() {
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp buildPartial() {
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp result = new com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp(this);
        result.type_ = type_;
        result.resultCode_ = resultCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp) {
          return mergeFrom((com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp other) {
        if (other == com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>sint32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int resultCode_ ;
      /**
       * <code>sint32 resultCode = 2;</code>
       * @return The resultCode.
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>sint32 resultCode = 2;</code>
       * @param value The resultCode to set.
       * @return This builder for chaining.
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 resultCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.chatnow.core.domain.protobuf.command.SendToUserCommandResp)
    }

    // @@protoc_insertion_point(class_scope:com.chatnow.core.domain.protobuf.command.SendToUserCommandResp)
    private static final com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp();
    }

    public static com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendToUserCommandResp>
        PARSER = new com.google.protobuf.AbstractParser<SendToUserCommandResp>() {
      @java.lang.Override
      public SendToUserCommandResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendToUserCommandResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendToUserCommandResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendToUserCommandResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chatnow.core.domain.protobuf.command.SendToUser.SendToUserCommandResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022send_to_user.proto\022(com.chatnow.core.d" +
      "omain.protobuf.command\"Z\n\021SendToUserComm" +
      "and\022\014\n\004type\030\001 \001(\021\022\027\n\017receiveUserName\030\002 \001" +
      "(\t\022\017\n\007content\030\003 \001(\t\022\r\n\005token\030\004 \001(\t\"9\n\025Se" +
      "ndToUserCommandResp\022\014\n\004type\030\001 \001(\021\022\022\n\nres" +
      "ultCode\030\002 \001(\021b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommand_descriptor,
        new java.lang.String[] { "Type", "ReceiveUserName", "Content", "Token", });
    internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chatnow_core_domain_protobuf_command_SendToUserCommandResp_descriptor,
        new java.lang.String[] { "Type", "ResultCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
